### ISSUE TITLE
Real URLs.

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#15]
We'll need to have permalinks for things. At the very least, domains, but likely domain + method/event too.

I looked briefly at https://erikringsmuth.github.io/app-router/ and it appears the best maintained in this space.  ( Not sure that polymer offers something more definitive… ? )

**Comment by kdzwinel** [comment]
We definitely need URLs for types so that it's easy to jump from property description to the corresponding type (same as in the current docs: https://developer.chrome.com/devtools/docs/protocol/1.1/dom#command-highlightNode ).

**Comment by kdzwinel** [comment]
Making type/event/method URLs work with current setup turned out to be much more complicated than I thought. Instead of spending time on that, I propose we change the approach a bit:

- use jekyll to generate separate static pages for domains (`/DOM`, `/Console`, etc.)
- use anchors for methods/types/events (`/DOM#method-getDocument`)

Pros of this solution:
- simple
- crawlable - solves SEO issue (#1)

Cons:
- page reload on domain change
- introduces build step (update `protocol.json` :arrow_right: run job that will generate html files for each domain :arrow_right: commit and push to repo)

@paulirish what do you think?

**Comment by paulirish** [comment]
sounds amazing. 

we can use `master` for things and let a bot like h5bp-bot do the compile and push to gh-pages: https://github.com/h5bp/html5boilerplate.com/blob/master/.travis.yml#L5-L32
