### ISSUE TITLE
Docs are returning 404

### ISSUE THREAD

**Issue by eligeske** [ChromeDevTools/debugger-protocol-viewer#162]
Looks like @devtools-bot might have broken docs with this commit https://github.com/ChromeDevTools/debugger-protocol-viewer/commit/b091d74acdd721e8304c77de112e92b8b148ec8f

Sample of deleted definitions:
https://github.com/ChromeDevTools/debugger-protocol-viewer/blob/b091d74acdd721e8304c77de112e92b8b148ec8f/pages/_data/v8.json

### What steps will reproduce the problem?

1. Open favorite browser, bes be krome, navigate to https://chromedevtools.github.io/devtools-protocol/tot/Network
2. See rendered page contains "Oops you hit a 404!" for Network details

### What is the expected result?
The Network page would contain definitions of Network

### What happens instead of that?
404 text displayed

![image](https://user-images.githubusercontent.com/3051711/95142792-837a5300-0742-11eb-97a0-db24a7ba1bdb.png)

![image](https://user-images.githubusercontent.com/3051711/95142919-d2c08380-0742-11eb-84f9-5f7f52a8b881.png)

![image](https://user-images.githubusercontent.com/3051711/95142814-92f99c00-0742-11eb-8dec-6d6c8c79458c.png)

**Comment by TimvdLippe** [comment]
Thanks a lot for filing this issue so quickly! It seems like we are back in action, as the issue got fixed in https://github.com/ChromeDevTools/debugger-protocol-viewer/commit/38166662522c415f0e4c0dae630599849958a98b It's unclear why the bot crashed/produced faulty output. However, since it recovered and (as far as I know) this is the first occurrence, I am assuming it was a fault in the matrix.

Please let us know if this happens again, because that would mean we have a structural issue that requires fixing. Once again, thank you so much for finding this issue and reporting it to us!
