### ISSUE TITLE
drop `paper-toolbar` and use `paper-scroll-header-panel`

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#22]
paper-toolbar's animated transition is not good.

most details in here: https://github.com/PolymerElements/paper-scroll-header-panel/issues/19#issuecomment-113610907
also relevant: https://github.com/PolymerElements/paper-toolbar/issues/27

**Comment by kdzwinel** [comment]
I've tried for 3h to get this animation right and wasn't able to get it right:
- paper-scroll-header-panel doesn't seem to work well when there is a custom element inside of it (got some cryptic errors - it took me a while to figure out what's wrong)
- it does not support title scaling animation out of the box, bunch of custom code has to be added and it doesn't work well with titles that break into two lines (since it just uses scale transform)
<img width="563" alt="screen shot 2015-07-07 at 01 56 59" src="https://cloud.githubusercontent.com/assets/985504/8536592/ca5061a2-2453-11e5-92b2-4585df6d1452.png">
- Chrome has some issues (both stable and canary) with scaling text - no idea what's causing it, on firefox it works just fine
<img width="569" alt="screen shot 2015-07-07 at 02 56 08" src="https://cloud.githubusercontent.com/assets/985504/8536568/99b7b25c-2453-11e5-9696-1fa8c0da708e.png">
- long titles look like this on mobile
<img width="360" alt="screen shot 2015-07-07 at 02 58 55" src="https://cloud.githubusercontent.com/assets/985504/8536616/172ae830-2454-11e5-812b-1914f44686a5.png">

**Comment by paulirish** [comment]
cc @blasten who may be interested ^

**Comment by paulirish** [comment]
We dropped it.
