### ISSUE TITLE
Animation domain is shown for ScreenOrientation domain

### ISSUE THREAD

**Issue by auchenberg** [ChromeDevTools/debugger-protocol-viewer#43]
Actual: 
1) Go to https://chromedevtools.github.io/debugger-protocol-viewer/ScreenOrientation/,
2) The animation domain is shown.

Expected:
1) Go to https://chromedevtools.github.io/debugger-protocol-viewer/ScreenOrientation/
2) ScreenOrientation domain is shown.

![chrome debugging protocol viewer - screenorientation 2016-03-14 16-34-22](https://cloud.githubusercontent.com/assets/173559/13763354/be70610a-ea02-11e5-95cd-f3cc25862997.png)

**Comment by kdzwinel** [comment]
Good catch!

@paulirish last time this happened it was because `protocol.json` got desynchronized with files in the `_domain` folder. My guess is that `protocol.json` was updated but `create-domain-files.js` haven't been runned. BTW I haven't seen your update script making any commits for a week now, can you please check that it's running?

**Comment by paulirish** [comment]
ooooops true.

**Comment by paulirish** [comment]
@kdzwinel hmmm this is apparently more complicated than it seems. can you help me in taking a look?

**Comment by paulirish** [comment]
ah, looks like you've already started: https://github.com/ChromeDevTools/debugger-protocol-viewer/compare/fix-domain-files-generator 

:)

**Comment by paulirish** [comment]
fix is live. thanks konrad!

**Comment by auchenberg** [comment]
Great work guys!  :muscle: :fire:
