### ISSUE TITLE
Adapt to new split protocol.json

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#54]
Will need @pavelfeldman's help

**Comment by pavelfeldman** [comment]
@paulirish how can I help you?

**Comment by kdzwinel** [comment]
OK, so according to the `protocol.json` from the TOT:

> The protocol.json has split into separate files. https://crbug.com/580337
> 
> One [for the browser](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/inspector/browser_protocol.json), one [for a V8 javascript environment](https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/platform/v8_inspector/js_protocol.json)

So now have: `browser_protocol.json` and `js_protocol.json` instead of `protocol.json`. As far as I understand in the viewer they should be represented like so:

- https://chromedevtools.github.io/debugger-protocol-viewer/tot/ ↔ `browser_protocol` + `js_protocol`
- https://chromedevtools.github.io/debugger-protocol-viewer/v8/ ↔ `js_protocol`

Which is problematic only for the `tot` as we currently do not support building docs and searching based on two files. From what I see, it's safe though to merge `browser_protocol.json` and `js_protocol.json` together (e.g. as a first step in the build process) and continue normally. I can take care of that, but please @paulirish let me know if my assumptions are correct.

**Comment by paulirish** [comment]
@kdzwinel yup you nailed it.

For our purposes we can totally merge those two JSON objects for our `tot` build.

Thanks for taking this!

**Comment by paulirish** [comment]
btw one small part of this is there are some domains we didn't know about before but are now merged into browser_protcol. (Such as the "Browser" domain: https://chromium.googlesource.com/chromium/src/+/master/third_party/WebKit/Source/core/inspector/browser_protocol.json#4186 )
