### ISSUE TITLE
The great redirect

### ISSUE THREAD

**Issue by paulirish** [ChromeDevTools/debugger-protocol-viewer#78]
### Proposal:

The published URL of the protocol docs move to `https://chromedevtools.github.io/devtools-protocol/`. 

- `devtools-protocol` repo's `master` branch continues to be the canonical*/reference location of the protocol files. it's issue tracker is used for protocol discussion.
- `devtools-protocol` repo's `gh-pages` branch will receive the source so it shows up online 
- `debugger-protocol-viewer` repo's `gh-pages` branch gets redirects set up. See #77
-  `debugger-protocol-viewer` repo's `master` branch will now be used for the source code of this API documentation

**Comment by paulirish** [comment]
@kdzwinel this sound good to you?

**Comment by kdzwinel** [comment]
SGTM, 'debugger-protocol-viewer' wasn't a great name - the docs had a hard time surfacing on the first page of google results.

Some questions/notes:

1) Are these 301 redirects? That'd be good for SEO.

2) Have you fixed your bot so that it doesn't touch `debugger-protocol-viewer` anymore and updates two branches (master&gh-pages) of `devtools-protocol` instead?

3) It'll be a bit of a PITA to push new version of `debugger-protocol-viewer` to `devtools-protocol` everytime we want to deploy :/ How we can automate it?

4) we don't have to use `gh-pages` for branch names anymore, you can pick any branch from repo settings.

**Comment by paulirish** [comment]
1. can't do 301's with jekyll. :(  rel=canonical along with a meta refresh
2. about to.
3. one more line for the bot. ;)
4. ah word. not a bad idea. :)

**Comment by paulirish** [comment]
okay!

1. https://chromedevtools.github.io/devtools-protocol/ now has all the old data from https://developer.chrome.com/devtools/docs/debugger-protocol FLESHED OUT. my my.
1. i [set up a redirect](https://github.com/GoogleChrome/devtools-docs/pull/315) for https://developer.chrome.com/devtools/docs/debugger-protocol so it should autoforward to the new url any hour now..
1. i call these two scripts to update everything: https://github.com/ChromeDevTools/devtools-protocol/tree/master/scripts
1. they're called every hour. so at most we have 1 hour delay between a non-protocol bump change here and a publish. (we could improve this more)

**Comment by kdzwinel** [comment]
Awesome 👏
